spring: 
  datasource: 
    url: jdbc:postgresql://localhost:5432/toma_asistencia
    username: adminasistencia
    password: postgres2019
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true